language: java

sudo: true

before_script:
- sudo apt-get install tightvncserver

cache:
  directories:
  - $HOME/.m2

#skip installation step
install: true

jdk:
- oraclejdk8

script:
- execute-on-script.sh mvn test