language: java

sudo: true

before_script:
- sudo apt-get install metacity xserver-xephyr

cache:
  directories:
  - $HOME/.m2

#skip installation step
install: true

jdk:
- oraclejdk8

script:
- Xephyr -screen 1024x768 :50 &- sleep 5- export DISPLAY=:50- metacity --sm-disable --replace 2> ~/tmp/metacity.err & 
- mvn -f pom.xml clean verify