language: java

sudo: true

before_script:
- sudo apt-get install tightvncserver
-  gunzip expect.tar.gz
 tar -xvf expect.tar

cache:
  directories:
  - $HOME/.m2

#skip installation step
install: true

jdk:
- oraclejdk8

script:
- bash script.sh mvn test