language: java

sudo: true

before_script:
- sudo apt-get install expect

cache:
  directories:
  - $HOME/.m2

#skip installation step
install: true

jdk:
- oraclejdk8

script:
- vncserver-x11
- bash script.sh mvn test