language: java

sudo: true

before_script:
- sudo apt-get install tightvncserver

cache:
  directories:
  - $HOME/.m2

#skip installation step
install: true

jdk:
- oraclejdk8

script:
- bash script.sh 
- vcnpasswd -t "o"
- mvn test
- expect "Password:"
- send "o"