language: java

sudo: true

before_script:
- sudo apt-get install xfce4 xfce4-goodies tightvncserver
- sudo apt-get install expect

cache:
  directories:
  - $HOME/.m2

#skip installation step
install: true

jdk:
- oraclejdk8

script:
- bash script2.sh mvn test